// TodosList
export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const SEARCH_TODO = 'SEARCH_TODO'
export const COMPLETE_TOGGLE_TODO = 'COMPLETE_TOGGLE_TODO'
export const ARCHIVE_TOGGLE_TODO = 'ARCHIVE_TOGGLE_TODO'

